# Generated by Django 5.2.5 on 2025-08-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parser_template', models.TextField(help_text='Шаблон ссылки для парсинга (с [replace_me] плейсхолдерами)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('demand_source', models.CharField(help_text='Например: Pixalate, Westcom и т.п.', max_length=255)),
                ('url_template', models.TextField(help_text='Шаблон ссылки кампании с {placeholders}')),
                ('qps_limit', models.PositiveIntegerField(default=0, help_text='Ограничение QPS если нужно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='core.aid')),
            ],
        ),
    ]
