# Generated by Django 5.2.5 on 2025-08-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='demand_source',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='qps_limit',
        ),
    ]
